name: Car Price Prediction Workflow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas numpy scikit-learn

    - name: Run MLflow Experiment
      run: |
        mlflow run MLProject/ --env-manager local

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: daffaamru
        password: dckr_pat_uHRTr_-pROT63FVTJio8JQ14f50

    # Menggunakan cd untuk masuk ke folder tempat Dockerfile berada
    - name: Build and Push Docker Image
      run: |
        cd MLProject
        docker build -t daffaamru/workflow-ci-sml:latest .
        docker push daffaamru/workflow-ci-sml:latest
